### ISSUE TITLE
Logo/icon proposal

### ISSUE THREAD

**Issue by jbeguna04** [jkobject/piple#11]
I would like to propose new designs of logo for your project:
Hope it can help you.
![image](https://user-images.githubusercontent.com/35353768/38603625-af2565ee-3da0-11e8-9215-415b5332b09f.png)
![image](https://user-images.githubusercontent.com/35353768/38603709-f1fa8aca-3da0-11e8-909d-c99dec3efb57.png)

Thank you,

**Comment by jkobject** [comment]
Hey ! 
Here is our logo for now (unfortunately we don't have a .PSD version):
[here ](https://drive.google.com/open?id=1GgbTeDqLSlzNZPZ82hYnv00kIzN-GbB9)
and here is our designs:
[here ]( https://drive.google.com/open?id=0B-dyutVWzmrzQk0wVGRWSXo0WGM
)[here](https://drive.google.com/open?id=0B-dyutVWzmrzOTBhMXdXWUI3OFk)
[there](https://drive.google.com/open?id=0B-dyutVWzmrzZEl5czYxZnJzZUk
)
[and there](https://drive.google.com/open?id=1R2lMZv7_qpvhXkxCSiPliOot2h8m8GmG) 
do you think you could do better than this? 
Would you like to help us designing ou wireframe ? our logo ? 
See what you can do.

**Comment by jbeguna04** [comment]
That is my proposal for the logos, I just did a proposal sir. Its up to you if it helps your project

**Comment by jkobject** [comment]
Well if you feel you can improve on our design and logos, feel free to do so !
if we find that there is a match with our values and ideas, we might entrust you with some paid missions regarding our designs

**Comment by jbeguna04** [comment]
Thank You for your time
