### ISSUE TITLE
cannot read property style of null

### ISSUE THREAD

**Issue by lamipaul** [jkobject/piple#25]
![image](https://user-images.githubusercontent.com/25902141/46400850-a7da6980-c6fb-11e8-9d73-0071bcf9cce5.png)
```
Uncaught TypeError: Cannot read property 'style' of null
    at getDOMStyleInfo (ReactNativeStyleResolver.js?431f:267)
    at ReactNativeStyleResolver.resolveWithNode (ReactNativeStyleResolver.js?431f:121)
    at eval (index.js?a21a:84)
    at createDOMProps (index.js?afbe:143)
    at View.setNativeProps (index.js?a21a:83)
    at AnimatedProps.AnimatedComponent._this._animatedPropsCallback [as _callback] (createAnimatedComponent.js?48e3:51)
    at AnimatedProps.update (AnimatedProps.js?d1a4:98)
    at eval (AnimatedValue.js?8be4:62)
    at Set.forEach (<anonymous>)
    at _flush (AnimatedValue.js?8be4:61)
```

Happens randomly when scrolling, tends to happen more with small screens. 
The error should come from the Animated view (line 470 in Bubble.js).

**Comment by lamipaul** [comment]
Complete log : 
Uncaught TypeError: Cannot read property 'style' of null
    at getDOMStyleInfo (ReactNativeStyleResolver.js?431f:267)
    at ReactNativeStyleResolver.resolveWithNode (ReactNativeStyleResolver.js?431f:121)
    at eval (index.js?a21a:84)
    at createDOMProps (index.js?afbe:143)
    at View.setNativeProps (index.js?a21a:83)
    at AnimatedProps.AnimatedComponent._this._animatedPropsCallback [as _callback] (createAnimatedComponent.js?48e3:51)
    at AnimatedProps.update (AnimatedProps.js?d1a4:98)
    at eval (AnimatedValue.js?8be4:62)
    at Set.forEach (<anonymous>)
    at _flush (AnimatedValue.js?8be4:61)
getDOMStyleInfo @ ReactNativeStyleResolver.js?431f:267
resolveWithNode @ ReactNativeStyleResolver.js?431f:121
(anonymous) @ index.js?a21a:84
createDOMProps @ index.js?afbe:143
setNativeProps @ index.js?a21a:83
AnimatedComponent._this._animatedPropsCallback @ createAnimatedComponent.js?48e3:51
update @ AnimatedProps.js?d1a4:98
(anonymous) @ AnimatedValue.js?8be4:62
_flush @ AnimatedValue.js?8be4:61
_updateValue @ AnimatedValue.js?8be4:340
(anonymous) @ AnimatedValue.js?8be4:307
onUpdate @ SpringAnimation.js?5fb6:208
start @ SpringAnimation.js?5fb6:120
start @ SpringAnimation.js?5fb6:128
animate @ AnimatedValue.js?8be4:304
start @ AnimatedImplementation.js?eb64:94
(anonymous) @ AnimatedImplementation.js?eb64:109
start @ AnimatedImplementation.js?eb64:100
(anonymous) @ AnimatedImplementation.js?eb64:304
start @ AnimatedImplementation.js?eb64:286
(anonymous) @ AnimatedImplementation.js?eb64:304
start @ AnimatedImplementation.js?eb64:286
Bubble._this.runEndMoveAnimation @ Bubble.js?e1af:1
shouldComponentUpdate @ Bubble.js?e1af:1
checkShouldComponentUpdate @ react-dom.development.js?cada:11346
updateClassInstance @ react-dom.development.js?cada:11755
updateClassComponent @ react-dom.development.js?cada:13154
beginWork @ react-dom.development.js?cada:13825
performUnitOfWork @ react-dom.development.js?cada:15864
workLoop @ react-dom.development.js?cada:15903
callCallback @ react-dom.development.js?cada:100
invokeGuardedCallbackDev @ react-dom.development.js?cada:138
invokeGuardedCallback @ react-dom.development.js?cada:187
replayUnitOfWork @ react-dom.development.js?cada:15311
renderRoot @ react-dom.development.js?cada:15963
performWorkOnRoot @ react-dom.development.js?cada:16561
performWork @ react-dom.development.js?cada:16483
performSyncWork @ react-dom.development.js?cada:16455
interactiveUpdates$1 @ react-dom.development.js?cada:16720
interactiveUpdates @ react-dom.development.js?cada:2150
dispatchInteractiveEvent @ react-dom.development.js?cada:4533
userStore.js?c0f4:1 userchanged
react-dom.development.js?cada:14227 The above error occurred in the <Bubble> component:
    in Bubble (at Chat.js:701)
    in div (created by View)
    in View (at Chat.js:847)
    in Chat (created by inject-Chat-with-sessionStore)
    in inject-Chat-with-sessionStore (created by inject-inject-Chat-with-sessionStore-with-groupStore)
    in inject-inject-Chat-with-sessionStore-with-groupStore (created by inject-inject-inject-Chat-with-sessionStore-with-groupStore-with-messageStore)
    in inject-inject-inject-Chat-with-sessionStore-with-groupStore-with-messageStore (created by inject-inject-inject-inject-Chat-with-sessionStore-with-groupStore-with-messageStore-with-userStore)
    in inject-inject-inject-inject-Chat-with-sessionStore-with-groupStore-with-messageStore-with-userStore (at WebHome.js:28)
    in div (created by View)
    in View (at WebHome.js:40)
    in Parameters (created by inject-Parameters-with-sessionStore)
    in inject-Parameters-with-sessionStore (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:574)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (at StackViewCard.js:12)
    in Card (at createPointerEventsContainer.js:28)
    in Container (at StackViewLayout.js:612)
    in div (created by View)
    in View (at StackViewLayout.js:470)
    in div (created by View)
    in View (at StackViewLayout.js:469)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:63)
    in div (created by View)
    in View (at Transitioner.js:169)
    in Transitioner (at StackView.js:21)
    in StackView (at createNavigator.js:59)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at DrawerView.js:87)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (created by DrawerLayout)
    in div (created by View)
    in View (created by DrawerLayout)
    in DrawerLayout (at DrawerView.js:84)
    in DrawerView (at createNavigator.js:59)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:574)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (at StackViewCard.js:12)
    in Card (at createPointerEventsContainer.js:28)
    in Container (at StackViewLayout.js:612)
    in div (created by View)
    in View (at StackViewLayout.js:470)
    in div (created by View)
    in View (at StackViewLayout.js:469)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:63)
    in div (created by View)
    in View (at Transitioner.js:169)
    in Transitioner (at StackView.js:21)
    in StackView (at createNavigator.js:59)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at App.js:110)
    in Provider (at App.js:109)
    in App (at index.js:9)

React will try to recreate this component tree from scratch using the error boundary you provided, NavigationContainer.
logCapturedError @ react-dom.development.js?cada:14227
logError @ react-dom.development.js?cada:14266
callback @ react-dom.development.js?cada:14948
callCallback @ react-dom.development.js?cada:10879
commitUpdateQueue @ react-dom.development.js?cada:10923
commitLifeCycles @ react-dom.development.js?cada:14378
commitAllLifeCycles @ react-dom.development.js?cada:15463
callCallback @ react-dom.development.js?cada:100
invokeGuardedCallbackDev @ react-dom.development.js?cada:138
invokeGuardedCallback @ react-dom.development.js?cada:187
commitRoot @ react-dom.development.js?cada:15604
completeRoot @ react-dom.development.js?cada:16619
performWorkOnRoot @ react-dom.development.js?cada:16564
performWork @ react-dom.development.js?cada:16483
performSyncWork @ react-dom.development.js?cada:16455
interactiveUpdates$1 @ react-dom.development.js?cada:16720
interactiveUpdates @ react-dom.development.js?cada:2150
dispatchInteractiveEvent @ react-dom.development.js?cada:4533
createNavigationContainer.js?cd8b:41 Uncaught TypeError: Cannot read property 'style' of null
    at getDOMStyleInfo (ReactNativeStyleResolver.js?431f:267)
    at ReactNativeStyleResolver.resolveWithNode (ReactNativeStyleResolver.js?431f:121)
    at eval (index.js?a21a:84)
    at createDOMProps (index.js?afbe:143)
    at View.setNativeProps (index.js?a21a:83)
    at AnimatedProps.AnimatedComponent._this._animatedPropsCallback [as _callback] (createAnimatedComponent.js?48e3:51)
    at AnimatedProps.update (AnimatedProps.js?d1a4:98)
    at eval (AnimatedValue.js?8be4:62)
    at Set.forEach (<anonymous>)
    at _flush (AnimatedValue.js?8be4:61)
getDOMStyleInfo @ ReactNativeStyleResolver.js?431f:267
resolveWithNode @ ReactNativeStyleResolver.js?431f:121
(anonymous) @ index.js?a21a:84
createDOMProps @ index.js?afbe:143
setNativeProps @ index.js?a21a:83
AnimatedComponent._this._animatedPropsCallback @ createAnimatedComponent.js?48e3:51
update @ AnimatedProps.js?d1a4:98
(anonymous) @ AnimatedValue.js?8be4:62
_flush @ AnimatedValue.js?8be4:61
_updateValue @ AnimatedValue.js?8be4:340
(anonymous) @ AnimatedValue.js?8be4:307
onUpdate @ SpringAnimation.js?5fb6:208
start @ SpringAnimation.js?5fb6:120
start @ SpringAnimation.js?5fb6:128
animate @ AnimatedValue.js?8be4:304
start @ AnimatedImplementation.js?eb64:94
(anonymous) @ AnimatedImplementation.js?eb64:109
start @ AnimatedImplementation.js?eb64:100
(anonymous) @ AnimatedImplementation.js?eb64:304
start @ AnimatedImplementation.js?eb64:286
(anonymous) @ AnimatedImplementation.js?eb64:304
start @ AnimatedImplementation.js?eb64:286
Bubble._this.runEndMoveAnimation @ Bubble.js?e1af:1
shouldComponentUpdate @ Bubble.js?e1af:1
checkShouldComponentUpdate @ react-dom.development.js?cada:11346
updateClassInstance @ react-dom.development.js?cada:11755
updateClassComponent @ react-dom.development.js?cada:13154
beginWork @ react-dom.development.js?cada:13825
performUnitOfWork @ react-dom.development.js?cada:15864
workLoop @ react-dom.development.js?cada:15903
renderRoot @ react-dom.development.js?cada:15943
performWorkOnRoot @ react-dom.development.js?cada:16561
performWork @ react-dom.development.js?cada:16483
performSyncWork @ react-dom.development.js?cada:16455
interactiveUpdates$1 @ react-dom.development.js?cada:16720
interactiveUpdates @ react-dom.development.js?cada:2150
dispatchInteractiveEvent @ react-dom.development.js?cada:4533
react-dom.development.js?cada:14227 The above error occurred in the <NavigationContainer> component:
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at DrawerView.js:87)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (created by DrawerLayout)
    in div (created by View)
    in View (created by DrawerLayout)
    in DrawerLayout (at DrawerView.js:84)
    in DrawerView (at createNavigator.js:59)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:574)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (at StackViewCard.js:12)
    in Card (at createPointerEventsContainer.js:28)
    in Container (at StackViewLayout.js:612)
    in div (created by View)
    in View (at StackViewLayout.js:470)
    in div (created by View)
    in View (at StackViewLayout.js:469)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:63)
    in div (created by View)
    in View (at Transitioner.js:169)
    in Transitioner (at StackView.js:21)
    in StackView (at createNavigator.js:59)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at App.js:110)
    in Provider (at App.js:109)
    in App (at index.js:9)

React will try to recreate this component tree from scratch using the error boundary you provided, NavigationContainer.
logCapturedError @ react-dom.development.js?cada:14227
logError @ react-dom.development.js?cada:14266
callback @ react-dom.development.js?cada:14948
callCallback @ react-dom.development.js?cada:10879
commitUpdateQueue @ react-dom.development.js?cada:10912
commitLifeCycles @ react-dom.development.js?cada:14378
commitAllLifeCycles @ react-dom.development.js?cada:15463
callCallback @ react-dom.development.js?cada:100
invokeGuardedCallbackDev @ react-dom.development.js?cada:138
invokeGuardedCallback @ react-dom.development.js?cada:187
commitRoot @ react-dom.development.js?cada:15604
completeRoot @ react-dom.development.js?cada:16619
performWorkOnRoot @ react-dom.development.js?cada:16564
performWork @ react-dom.development.js?cada:16483
performSyncWork @ react-dom.development.js?cada:16455
interactiveUpdates$1 @ react-dom.development.js?cada:16720
interactiveUpdates @ react-dom.development.js?cada:2150
dispatchInteractiveEvent @ react-dom.development.js?cada:4533
createNavigationContainer.js?cd8b:41 Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (react-dom.development.js?cada:145)
    at invokeGuardedCallback (react-dom.development.js?cada:187)
    at commitRoot (react-dom.development.js?cada:15604)
    at completeRoot (react-dom.development.js?cada:16619)
    at performWorkOnRoot (react-dom.development.js?cada:16564)
    at performWork (react-dom.development.js?cada:16483)
    at performSyncWork (react-dom.development.js?cada:16455)
    at interactiveUpdates$1 (react-dom.development.js?cada:16720)
    at interactiveUpdates (react-dom.development.js?cada:2150)
    at dispatchInteractiveEvent (react-dom.development.js?cada:4533)
invokeGuardedCallbackDev @ react-dom.development.js?cada:145
invokeGuardedCallback @ react-dom.development.js?cada:187
commitRoot @ react-dom.development.js?cada:15604
completeRoot @ react-dom.development.js?cada:16619
performWorkOnRoot @ react-dom.development.js?cada:16564
performWork @ react-dom.development.js?cada:16483
performSyncWork @ react-dom.development.js?cada:16455
interactiveUpdates$1 @ react-dom.development.js?cada:16720
interactiveUpdates @ react-dom.development.js?cada:2150
dispatchInteractiveEvent @ react-dom.development.js?cada:4533
react-dom.development.js?cada:14227 The above error occurred in the <NavigationContainer> component:
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:574)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (at StackViewCard.js:12)
    in Card (at createPointerEventsContainer.js:28)
    in Container (at StackViewLayout.js:612)
    in div (created by View)
    in View (at StackViewLayout.js:470)
    in div (created by View)
    in View (at StackViewLayout.js:469)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:63)
    in div (created by View)
    in View (at Transitioner.js:169)
    in Transitioner (at StackView.js:21)
    in StackView (at createNavigator.js:59)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at App.js:110)
    in Provider (at App.js:109)
    in App (at index.js:9)

React will try to recreate this component tree from scratch using the error boundary you provided, NavigationContainer.
logCapturedError @ react-dom.development.js?cada:14227
logError @ react-dom.development.js?cada:14266
callback @ react-dom.development.js?cada:14948
callCallback @ react-dom.development.js?cada:10879
commitUpdateQueue @ react-dom.development.js?cada:10912
commitLifeCycles @ react-dom.development.js?cada:14378
commitAllLifeCycles @ react-dom.development.js?cada:15463
callCallback @ react-dom.development.js?cada:100
invokeGuardedCallbackDev @ react-dom.development.js?cada:138
invokeGuardedCallback @ react-dom.development.js?cada:187
commitRoot @ react-dom.development.js?cada:15604
completeRoot @ react-dom.development.js?cada:16619
performWorkOnRoot @ react-dom.development.js?cada:16564
performWork @ react-dom.development.js?cada:16483
performSyncWork @ react-dom.development.js?cada:16455
interactiveUpdates$1 @ react-dom.development.js?cada:16720
interactiveUpdates @ react-dom.development.js?cada:2150
dispatchInteractiveEvent @ react-dom.development.js?cada:4533
createNavigationContainer.js?cd8b:41 Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (react-dom.development.js?cada:145)
    at invokeGuardedCallback (react-dom.development.js?cada:187)
    at commitRoot (react-dom.development.js?cada:15604)
    at completeRoot (react-dom.development.js?cada:16619)
    at performWorkOnRoot (react-dom.development.js?cada:16564)
    at performWork (react-dom.development.js?cada:16483)
    at performSyncWork (react-dom.development.js?cada:16455)
    at interactiveUpdates$1 (react-dom.development.js?cada:16720)
    at interactiveUpdates (react-dom.development.js?cada:2150)
    at dispatchInteractiveEvent (react-dom.development.js?cada:4533)
invokeGuardedCallbackDev @ react-dom.development.js?cada:145
invokeGuardedCallback @ react-dom.development.js?cada:187
commitRoot @ react-dom.development.js?cada:15604
completeRoot @ react-dom.development.js?cada:16619
performWorkOnRoot @ react-dom.development.js?cada:16564
performWork @ react-dom.development.js?cada:16483
performSyncWork @ react-dom.development.js?cada:16455
interactiveUpdates$1 @ react-dom.development.js?cada:16720
interactiveUpdates @ react-dom.development.js?cada:2150
dispatchInteractiveEvent @ react-dom.development.js?cada:4533
App.js?14b1:1 Uncaught TypeError: this._stores.cancel is not a function
    at App.componentWillUnmount (App.js?14b1:1)
    at App.f (index.module.js?327f:698)
    at callComponentWillUnmountWithTimer (react-dom.development.js?cada:14281)
    at HTMLUnknownElement.callCallback (react-dom.development.js?cada:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?cada:138)
    at invokeGuardedCallback (react-dom.development.js?cada:187)
    at safelyCallComponentWillUnmount (react-dom.development.js?cada:14288)
    at commitUnmount (react-dom.development.js?cada:14495)
    at unmountHostComponents (react-dom.development.js?cada:14797)
    at commitDeletion (react-dom.development.js?cada:14828)
componentWillUnmount @ App.js?14b1:1
f @ index.module.js?327f:698
callComponentWillUnmountWithTimer @ react-dom.development.js?cada:14281
callCallback @ react-dom.development.js?cada:100
invokeGuardedCallbackDev @ react-dom.development.js?cada:138
invokeGuardedCallback @ react-dom.development.js?cada:187
safelyCallComponentWillUnmount @ react-dom.development.js?cada:14288
commitUnmount @ react-dom.development.js?cada:14495
unmountHostComponents @ react-dom.development.js?cada:14797
commitDeletion @ react-dom.development.js?cada:14828
commitAllHostEffects @ react-dom.development.js?cada:15417
callCallback @ react-dom.development.js?cada:100
invokeGuardedCallbackDev @ react-dom.development.js?cada:138
invokeGuardedCallback @ react-dom.development.js?cada:187
commitRoot @ react-dom.development.js?cada:15569
completeRoot @ react-dom.development.js?cada:16619
performWorkOnRoot @ react-dom.development.js?cada:16564
performWork @ react-dom.development.js?cada:16483
performSyncWork @ react-dom.development.js?cada:16455
interactiveUpdates$1 @ react-dom.development.js?cada:16720
interactiveUpdates @ react-dom.development.js?cada:2150
dispatchInteractiveEvent @ react-dom.development.js?cada:4533
react-dom.development.js?cada:14227 The above error occurred in the <NavigationContainer> component:
    in NavigationContainer (at App.js:110)
    in Provider (at App.js:109)
    in App (at index.js:9)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js?cada:14227
logError @ react-dom.development.js?cada:14266
update.callback @ react-dom.development.js?cada:14919
callCallback @ react-dom.development.js?cada:10879
commitUpdateQueue @ react-dom.development.js?cada:10912
commitLifeCycles @ react-dom.development.js?cada:14397
commitAllLifeCycles @ react-dom.development.js?cada:15463
callCallback @ react-dom.development.js?cada:100
invokeGuardedCallbackDev @ react-dom.development.js?cada:138
invokeGuardedCallback @ react-dom.development.js?cada:187
commitRoot @ react-dom.development.js?cada:15604
completeRoot @ react-dom.development.js?cada:16619
performWorkOnRoot @ react-dom.development.js?cada:16564
performWork @ react-dom.development.js?cada:16483
performSyncWork @ react-dom.development.js?cada:16455
interactiveUpdates$1 @ react-dom.development.js?cada:16720
interactiveUpdates @ react-dom.development.js?cada:2150
dispatchInteractiveEvent @ react-dom.development.js?cada:4533
react-dom.development.js?cada:14227 The above error occurred in the <App> component:
    in App (at index.js:9)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js?cada:14227
logError @ react-dom.development.js?cada:14266
update.callback @ react-dom.development.js?cada:14919
callCallback @ react-dom.development.js?cada:10879
commitUpdateQueue @ react-dom.development.js?cada:10912
commitLifeCycles @ react-dom.development.js?cada:14397
commitAllLifeCycles @ react-dom.development.js?cada:15463
callCallback @ react-dom.development.js?cada:100
invokeGuardedCallbackDev @ react-dom.development.js?cada:138
invokeGuardedCallback @ react-dom.development.js?cada:187
commitRoot @ react-dom.development.js?cada:15604
completeRoot @ react-dom.development.js?cada:16619
performWorkOnRoot @ react-dom.development.js?cada:16564
performWork @ react-dom.development.js?cada:16483
performSyncWork @ react-dom.development.js?cada:16455
interactiveUpdates$1 @ react-dom.development.js?cada:16720
interactiveUpdates @ react-dom.development.js?cada:2150
dispatchInteractiveEvent @ react-dom.development.js?cada:4533
react-dom.development.js?cada:145 Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (react-dom.development.js?cada:145)
    at invokeGuardedCallback (react-dom.development.js?cada:187)
    at commitRoot (react-dom.development.js?cada:15604)
    at completeRoot (react-dom.development.js?cada:16619)
    at performWorkOnRoot (react-dom.development.js?cada:16564)
    at performWork (react-dom.development.js?cada:16483)
    at performSyncWork (react-dom.development.js?cada:16455)
    at interactiveUpdates$1 (react-dom.development.js?cada:16720)
    at interactiveUpdates (react-dom.development.js?cada:2150)
    at dispatchInteractiveEvent (react-dom.development.js?cada:4533)

**Comment by jkobject** [comment]
this function appears because of a wrong use of shouldcomponent updtate where it is stipulated that it should not change the state of the component. This is because the function is called when the state is changing that is why is even gives what the nextState will be. setting new states will cause a rerender which is (in addition to be useless, will create (on the web only) a parallel re-rendering of the component, thus the shouldcomponent update will cause two parallel animation and thus the error. I have thus removed all the setStates as they should work out without putting them again this function. There is some states that do not appear to get updtated yet. However one can play with the other parts of the lifecycle (setting the state after the rerendering or prior to it but not during it (i.e. in the should component update)
