### ISSUE TITLE
problem with ionic serve cmd

### ISSUE THREAD

**Issue by jkobject** [jkobject/PiPle#4]
```
Error: Cannot find module '/Users/jeremie/piple/node_modules/@ionic/app-scripts'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/ionic-angular/app-scripts.js:9:16)
    at next (native)
    at /usr/local/lib/node_modules/ionic/node_modules/tslib/tslib.js:103:75
    at Object.__awaiter (/usr/local/lib/node_modules/ionic/node_modules/tslib/tslib.js:99:16)
    at Object.importAppScripts (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/ionic-angular/app-scripts.js:7:20)
    at /usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/ionic-angular/serve.js:13:48
```

**Comment by jkobject** [comment]
there is a set of commands missing from the readme
I think that it is something like  ```add android```

**Comment by prosenzweig** [comment]
Can you tell me what is your version of node.js ? ( with the command node -v)
İf you installed node 8 please uninstall and install node 7 stable version. This solved error and you will could use ionic3, angular 4 . Enjoy ! :)

https://stackoverflow.com/questions/44381358/error-cannot-find-module-ionic-app-scripts

**Comment by jkobject** [comment]
ok, I had node 6, node 9 is the current stable version but I went to node 7 using  and I forced my previous binding to this version 
```
sudo npm install n -g
n 7
npm rebuild node-sass --force
```

the server now runs but only display a typescript error  on multiple files from node

**Comment by jkobject** [comment]
this is the problem 
```Duplicate identifier 'Promise' ```in es6 es2015 and es5

**Comment by prosenzweig** [comment]
It seems SeGirardot just deal with this problem yesterday morning :)

**Comment by SeGirardot** [comment]
Try using

`npm install -g ionic`

It should tell you what dependencies you might be lacking :)

If this is not the source of the problem you should try to delete the line n°13 of the file named "firebase.app.module.d.ts" from PiPle/node_modules/angularfire2/app

Tell us if there is still the issue after trying this ! ^^

**Comment by jkobject** [comment]
well It did not help. 
I don't think it is on firebase the problem, at least not for me. I don't even have installed it.

**Comment by SeGirardot** [comment]
Then I will try to reinstall it myself and post the steps here :)

**Comment by jkobject** [comment]
you should start from a blank session without anything installed. 
and then you try to do everystep to install piple and you write them in the read me and specify to look if they have the versions before. 

I did ```npm list````
and I have this which is not beautifull at all
```
npm ERR! peer dep missing: firebase@^3.6.6, required by angularfire2@4.0.0-rc0
npm ERR! extraneous: cordova-android@6.3.0 /Users/jeremie/piple/node_modules/cordova-android
npm ERR! extraneous: cordova-ios@4.5.3 /Users/jeremie/piple/node_modules/cordova-ios
npm ERR! extraneous: cordova-plugin-device@1.1.4 /Users/jeremie/piple/node_modules/cordova-plugin-device
npm ERR! extraneous: cordova-plugin-splashscreen@4.0.3 /Users/jeremie/piple/node_modules/cordova-plugin-splashscreen
npm ERR! extraneous: cordova-plugin-statusbar@2.2.2 /Users/jeremie/piple/node_modules/cordova-plugin-statusbar
npm ERR! extraneous: cordova-plugin-whitelist@1.3.1 /Users/jeremie/piple/node_modules/cordova-plugin-whitelist
npm ERR! extraneous: firestore@1.1.6 /Users/jeremie/piple/node_modules/firestore
npm ERR! extraneous: ionic-plugin-keyboard@2.2.1 /Users/jeremie/piple/node_modules/ionic-plugin-keyboard
npm ERR! extraneous: n@2.1.8 /Users/jeremie/piple/node_modules/n;)

**Comment by SeGirardot** [comment]
I did something way more barbarian XD and I hope this will help you ! You should check the blazing new Readme that I uploaded :)

**Comment by SeGirardot** [comment]
You should try to uninstall everything or starting by the cordova install from the readme and you should be set :)
